### ISSUE TITLE
Gives random time or one hour behind

### ISSUE THREAD

**Issue by imperator-maximus** [sstaub/NTP#12]
Hi,
I was not sucessful to get this lib running with currect time and I ran into two different issues:

1. first day time is correct but at midnight it goes back one hour and stays there forever (time+date is exact but one hour behind). I have this behaviour if I ask once a minute (via serial ) for time (ntp.update() + ntp.hours(),...). This is part of a huge clock project so it is difficult to debug.

2. So I thought just to debug it via web interface: 
  ntp.update();  s+=ntp.formattedTime("%Y-%m-%d %H:%M:%S"); 

In this scenario update does not run once a second or minute just a few time I reload page. Result: more or less random time (e.g. 30 years ahead, totally wrong time of day).

You can find full source code here: https://github.com/flyingdogsoftware/Tower-Clock-Wifi/blob/master/src/main.cpp

Thank you!

**Comment by Bolukan** [comment]
Do you considered a problem of your code and not the library.
I suggest to add ntp.update(); to your loop and further compare your code to the examples of this library for further differences. Success with your project!

**Comment by imperator-maximus** [comment]
yes I considered it and it would be great to find a solution.
In example there is in main loop
  ntp.update();
and
  delay(1000);

But I cannot do a delay in main loop because I am waiting for serial input. That is the reason I am doing update different. So it would be ok to make that update without 1 sec delay? Will there be an internet connection for each ntp.update()?

**Comment by sstaub** [comment]
Try to use my ticker library instead of delay(), because delay blocks the processor.

**Comment by imperator-maximus** [comment]
Thank you. With great ticker library this works perfect now and I can finish my project!
