### ISSUE TITLE
Compile error: 'NTP' does not name a type

### ISSUE THREAD

**Issue by ctgreybeard** [sstaub/NTP#19]
I'm having trouble figuring this one out ...

I'm writing something on a Raspberry Pi Pico W. I've just started out and when I tried adding in the NTP code I get this compile error but it isn't making any sense to me.

My code:
```
#include <ArduinoLog.h>

#include <WiFi.h>
// #include <WiFiClient.h>
// #include <WiFiServer.h>
#include <WiFiUdp.h>

#include "NTP.h"

const char* ssid = "myssid";
const char* wifiPassword = "mypassword";

WiFiUDP wifiUdp;

NTP npt(wifiUdp);

void setup() {
  delay(1000);

  Serial.begin(9600);
  if (!Serial) {
    delay(500);
  }

  Log.begin(LOG_LEVEL_VERBOSE, &Serial);

  Log.infoln("Starting...");

  WiFi.begin(ssid, wifiPassword);
  while (WiFi.status() != WL_CONNECTED) {
    Serial.println("Connecting ...");
    delay(500);
  }
  Serial.println("Connected");

  ntp.ruleDST("EDT", Second, Sun, Mar, 2, -240);  // second sunday in march 2:00, timetone -240min (-5 GMT + 1h summertime offset)
  ntp.ruleSTD("EST", First, Sun, Nov, 2, -300);   // first sunday in november 2:00, timezone -300min (-5 GMT)
  ntp.begin();
  Serial.println("start NTP");
}

void loop() {
  delay(1000);
  ntp.update();
  Log.infoln("Tick... %s", ntp->formattedTime());
}
```

Throws the error:
```
/Users/xxx/Documents/Arduino/Layer_Clock_NTP/Layer_Clock_NTP.ino:15:1: error: 'NTP' does not name a type
   15 | NTP npt(wifiUdp);
      | ^~~
```

Any idea what's the error? Hovering over the "NTP" shows "class NTP" so it looks like the IDE has the idea but the compiler doesn't.

**Comment by sstaub** [comment]
It is a typo, NTP npt(wifiUdp); is wrong use NTP npt(wifiUdp);

**Comment by ctgreybeard** [comment]
Thanks for finding that but it doesn't change the error at all ...

```
/Users/xxx/Documents/Arduino/Layer_Clock_NTP/Layer_Clock_NTP.ino:15:1: error: 'NTP' does not name a type
   15 | NTP ntp(wifiUdp);
      | ^~~
```

**Comment by sstaub** [comment]
Did you add the library to the IDE?

**Comment by ctgreybeard** [comment]
I think I've found the problem.

The board library I am using: Raspberry Pi Pico/RP2040 already includes an NTP module inside the WiFi module. So I think the compiler gets confused. I'm adjusting to use the included NTP but it doesn't have the same functionality as this one which is too bad.

The docs are at https://arduino-pico.readthedocs.io/en/latest/wifintp.html

**Comment by sstaub** [comment]
Which core did you use?

**Comment by bartgrefte** [comment]
@sstaub 
Same error here while trying to find a NTP-library with DST for a Raspberry Pi Pico W.

I'm guessing by core you mean https://github.com/earlephilhower/arduino-pico ? version 3.7.2 here.
