### ISSUE TITLE
library fails to compile

### ISSUE THREAD

**Issue by sjoerdtimmer** [sstaub/NTP#2]
Hi, 
I'm probably using this wrong but for me the library fails to compile with the error:
```
*** [.pioenvs/nodemcuv2/src/main.cpp.o] Error 1
In file included from .piolibdeps/NTP_ID5438/NTP.cpp:23:0:
.piolibdeps/NTP_ID5438/NTP.h:46:12: error: expected ')' before '&' token 
NTP(UDP& udp);
^
```

It also raises an error: src/main.cpp:10:18: fatal error: WiFi.h: No such file or directory
But I assumed that was ok since I have ESP8266WiFi.h
Is WiFi.h part of some dependency that I need to install?

I'm on PlatformIO version 3.6.0a3 on up-to-date archlinux x86_64 machine

**Comment by Bolukan** [comment]
As the example is for the ESP32 you have to replace the reference to WiFi.h with ESP8266WiFi.h
Or add #if defined(ESP8266) and #if defined(ESP32) statements, etc and do a pull request.

As the above is necessary for the Udp reference the first error will be related to the second

**Comment by sjoerdtimmer** [comment]
I think the problem is more complex. I already have an include of <ESP8266WiFi.h> at the top and removing the <WiFi.h> does indeed remove the error about that but the Udp symbol is still not found and the syntax error about the expected ')' remains.

**Comment by Bolukan** [comment]
The library does not reference to UDP. So your reference to NTP should be after the line referencing WiFiUdp. If also this not solve your problem, please show some relevant code.
(@sstaub, do you have reasons to not include is a reference in the library, like board specific Udp implementations?)

**Comment by sstaub** [comment]
It seems Arduino is broken with the use of the Wifi libs.
The constructor was from the NTPClient library from Arduino https://github.com/arduino-libraries/NTPClient.
With my ESP32 example on PIO I get following error message:
_no instance of overloaded function "WiFiClass::begin" matches the argument list -- argument types are: (const char *, const char *) -- object type is: WiFiClass_
!!! But I can build and upload, when I delete the Arduino WiFi lib form PIO, that is also very obscure.
I have tried the original library with the Basic.ino example with a MKR1000 board on the Arduino IDE and I can't build and get similar error messages as when I use my library with WIFI_UDP.ino with MKR1000 or ESP32 on PIO.

**Comment by sjoerdtimmer** [comment]
Yep, I have included WiFiUdp.h before including NTP.h. 
I have now added your example to a new platformio project (with the minor change from WiFi.h to ESP8266WiFi.h). This is the contents of my platformio env:
```
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps = 5438
```
This reproduces the error.

This is really strange. It is starting to look more like a platformio bug now...
I have already included lib_ldf_mode = deep+ to exclude some issue with the dependency scanner but that did not solve anything.

Any thoughts?

**Comment by sjoerdtimmer** [comment]
If I include WiFiUdp.h from NTP.h this problem goes away (in favour of the next error which I'll describe below).

I think platformio compiles libraries into separate object files before compiling the main source. This means that includes from the main sketch are not visible when compiling NTP.h. Maybe in esp32 platform the udp headers are included by default? 
I think the way this should be implemented is using an #ifdef to include either Udp.h or WifFiUdp.h.

The problem I'm facing now is even more elusive. Maybe my judgment of the situation is completely off and have introduced this with the extra include...? 
```
.piolibdeps/NTP_ID5438/NTP.cpp: In constructor 'NTP::NTP(UDP&)':
.piolibdeps/NTP_ID5438/NTP.cpp:25:18: error: array used as initializer
NTP::NTP(UDP& udp) {
^
.piolibdeps/NTP_ID5438/NTP.cpp:25:18: error: array used as initializer
.piolibdeps/NTP_ID5438/NTP.cpp:25:18: error: array used as initializer
```

**Comment by sstaub** [comment]
I figured out same small behavior with const in password / SSID, and I can compile with ESP32.
So I investigate further.

**Comment by sjoerdtimmer** [comment]
You are right. It is better (and sufficient) to include Udp.h in NTP.h. That should work for esp32 as well as esp8266. (I assume you mean Udp.h instead of UDP.h)

Any hints regarding the initializer array??

**Comment by sstaub** [comment]
with release 1.2.0 it should work, I can compile with an Adafruit Huzzah8266 b board.
