### ISSUE TITLE
Usage with WiFi or Ethernet

### ISSUE THREAD

**Issue by DO7LZ** [sstaub/NTP#20]
First of all thank you for this really (!) good libary. I'd like to propose an enhancement:
Is it possible to move the definition of the UDP "Connector" (instance of `EthernetUDP` or `WiFiUDP`) away from the constructor to the `init()` or `begin()` method? I'd like to check before, if an internet connection is possible via wifi or Ethernet (cable).
I tried several ways to accomplish this with Release 1.6 from PlatformIO registry. But I didn't get the clue. 
Thanks
Matthias

**Comment by sstaub** [comment]
This is not easy to do and will need a change of 5he whole API. But you can try to make two instances, one for WIFI the other for LAN. But the problem is the libraries may block the whole code execution when there is no connection. Or try if you can to make the instances in setup after checking if there is a connection.

**Comment by DO7LZ** [comment]
Ok. By now, the problem may be solved.
Documentation (for my future me):

1st idea - two instances (working by now)
```
#include <EthernetUdp.h>
#include <WiFiUdp.h>
#include "NTP.h"

EthernetUDP ethUDP;
NTP ethNTP(ethUDP);
WiFiUDP wifiUDP;
NTP wifiNTP(wifiUDP);

void setup() {
  if (ethernetAvailable) {
      ethNTP.ruleDST("CEST", Last, Sun, Mar, 2, 120); // last sunday in march 2:00, timetone +120min (+1 GMT + 1h summertime offset)
      ethNTP.ruleSTD("CET", Last, Sun, Oct, 3, 60); // last sunday in october 3:00, timezone +60min (+1 GMT)
      ethNTP.begin();
      ethNTP.update();
  } else if (wifiAvailable) {
      wifiNTP.ruleDST("CEST", Last, Sun, Mar, 2, 120); // last sunday in march 2:00, timetone +120min (+1 GMT + 1h summertime offset)
      wifiNTP.ruleSTD("CET", Last, Sun, Oct, 3, 60); // last sunday in october 3:00, timezone +60min (+1 GMT)
      wifiNTP.begin();
      wifiNTP.update();
  }
}

void loop() {
  delay(1000);
  if (ethernetAvailable) {
    Ethernet.maintain();
    ethNTP.update();
  } else if (wifiAvailable) {
    wifiNTP.update();
  }
}
```

2nd idea - preallocated pointer and later definition in setup (results in some random processed timestamps). In accordance with https://forum.arduino.cc/t/delcaring-a-global-object/37107. (Fails maybe due to my rookie pointer skills.)
```
#include <EthernetUdp.h>
#include <WiFiUdp.h>
#include "NTP.h"

EthernetUDP ethUDP;
WiFiUDP wifiUDP;
void* operator new(size_t size) {return malloc(size); }
void operator delete(void* ptr) { free(ptr); }
NTP* sntp = NULL;

void setup() {
  if (ethernetAvailable) {
      sntp = new NTP(ethUDP);
      sntp->ruleDST("CEST", Last, Sun, Mar, 2, 120); // last sunday in march 2:00, timetone +120min (+1 GMT + 1h summertime offset)
      sntp->ruleSTD("CET", Last, Sun, Oct, 3, 60); // last sunday in october 3:00, timezone +60min (+1 GMT)
      sntp->begin();
      sntp->update();
  } else if (wifiAvailable) {
      sntp = new NTP(wifiUDP);
      sntp->ruleDST("CEST", Last, Sun, Mar, 2, 120); // last sunday in march 2:00, timetone +120min (+1 GMT + 1h summertime offset)
      sntp->ruleSTD("CET", Last, Sun, Oct, 3, 60); // last sunday in october 3:00, timezone +60min (+1 GMT)
      sntp->begin();
      sntp->update();
  }
}

void loop() {
  delay(1000);
  if (ethernetAvailable || wifiAvailable) {
    sntp->update();
  }
}
```

I will do some more testing tomorrow and report.

**Comment by DO7LZ** [comment]
Ok. Solution 1 worked as expected. No more problems occurred. The switching between Ethernet and WiFi after `setup()` in case of connection problems will raise some other problems but this feature will be postponed in my project. Thanks for the support.
