### ISSUE TITLE
Feature request: Get_UTC and get_localtime

### ISSUE THREAD

**Issue by TKaluza** [sstaub/NTP#3]
Thanks for this great lib!
I do not know if this is a good feature request, because the requested functionality  is a (bit) more then this lib is probably ought to do. But it would be great. :smile: 

Adding two functions would be great; I like to set my RTC to epoch and sometimes I need to display the localtime. As far as I know, in the ESP 8266 Arduino code there's not yet a working solution for converting between time zone. 

So maybe you could add the function `ntp.localtime()`, which would display the the time of the ntp object, but if you put in it another the epoch or a timestamp `ntp.localtime(epoch)` it would just convert the given time into the "local" epoch (with timezone and DST). 

`ntp.gmttime() `could result in the actual epoch without any timezone information and DSTs. 
and `ntp.gmttime(epoch)` would convert the epoch back to UTC/GMT time, based on the DST information stored in the object.

Problems: Nesting will result in wrong times `ntp.gmttime(ntp.gmttime(epoch))`

It would also be possible to have different ntp objects: 
ntp
ntp_ger
ntp_us
which could hold different time zone. 

But maybe this is "too much" for this library. Just my two cents.

Thank you very much!

**Comment by sstaub** [comment]
The goal of the library is to be simple. There are many other libraries that gives you the options you need. The problems you have can solved by easy calculations, have a look at the wiki for start 
https://de.wikipedia.org/wiki/Network_Time_Protocol

**Comment by TKaluza** [comment]
Thanks for the answer and yes, that is true. I can understand that.
