### ISSUE TITLE
DST syntax question

### ISSUE THREAD

**Issue by esp32noob** [sstaub/NTP#4]
Thank you for your library, it's awesome.

We have recently changed to DST however my time did not change.  Can you please review my settings and identify my mistake.  The time should have gone forward by 1 hour at 3am on 29/9/2019.  I'm assuming that the daily time update happened correctly as it normally does.

  NTPServer.ntpServer(NTPServerName);
  NTPServer.updateInterval(NTPRefreshTime);
  NTPServer.ruleSTD("NZST", First, Sun, Apr, 2, 12 * 60);
  // first sunday in April at 3:00, timezone 12 hours
  NTPServer.ruleDST("NZDT", Last, Sun, Sep, 3, 12 * 60 + 60);
  // last sunday in September at 3:00, timezone 13 hours
  NTPServer.begin();

Thanks

**Comment by sstaub** [comment]
You swapped DST and STD:
NTPServer.ntpServer(NTPServerName);
NTPServer.updateInterval(NTPRefreshTime);
NTPServer.ruleDST("NZST", First, Sun, Apr, 2, 12 * 60);
// first sunday in April at 3:00, timezone 12 hours
NTPServer.ruleSDT("NZDT", Last, Sun, Sep, 3, 12 * 60 + 60);
// last sunday in September at 3:00, timezone 13 hours
NTPServer.begin();
