### ISSUE TITLE
epoch() does not return updated time

### ISSUE THREAD

**Issue by morres83** [sstaub/NTP#5]
The inline function epoch() returns utcCurrent.
utcCurrent is not updated if not any method calls private method currentTime() previously.
Consequently, in this case, epoch() will always return the value of the first sync (because ntp.begin() calls currentTime() once).

**Comment by sstaub** [comment]
I have updated the epoch() function. Can you please test it, so I can make  a release?

**Comment by morres83** [comment]
I have tested it on ESP8266 and it works as expected now.
Thank you.

**Comment by sstaub** [comment]
Released, thank you for your advice.
